# coding: utf-8

"""
    Ratings API

    Service which holds ratings of various targets, like recipes.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rating
from rating.api.targets_api import TargetsApi  # noqa: E501
from rating.rest import ApiException


class TestTargetsApi(unittest.TestCase):
    """TargetsApi unit test stubs"""

    def setUp(self):
        self.api = rating.api.targets_api.TargetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_targets_targetnamespace(self):
        """Test case for get_targets_targetnamespace

        Lists all targets currently in the database.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
