# coding: utf-8

"""
    Search API

    Search API is a REST-like API which wraps the underlying ElasticSearch service for most common use cases. While this API is called the \"search\" service, in practice it acts as the main data engine for various Kesko services, providing high performance endpoints for fetching recipe, product, offer, store and article data.    API requests are only served over HTTPS, using TLS 1.0, 1.1, and 1.2. Requests will not be honored over plaintext HTTP.    Use of `accept: application/json` and `content-type: application/json` headers is required when applicable.    The API uses UTF-8 character encoding for all responses. Some fields may include characters that are not in the ASCII range.    As every other Kesko API service in this hackathon, authentication is accomplished by providing `Ocp-Apim-Subscription-Key` header with your subscription key as the value.    Submitting excessive requests to the server may result in a HTTP 429 Too Many Requests status code and temporary limitations to your Subscription. We kindly ask that you to limit the concurrency of your requests and/or insert 50 – 100 milliseconds of delay between the requests you send to the server. (i.e., 10 requests per second on average), since this environment doesn't run with the same specs as the real production instance.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class PayloadAllOfView(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'limit': 'int',
        'offset': 'int',
        'show_facets': 'PayloadAllOfViewShowFacets',
        'sort_by': 'list[object]'
    }

    attribute_map = {
        'limit': 'limit',
        'offset': 'offset',
        'show_facets': 'showFacets',
        'sort_by': 'sortBy'
    }

    def __init__(self, limit=None, offset=None, show_facets=None, sort_by=None, local_vars_configuration=None):  # noqa: E501
        """PayloadAllOfView - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._limit = None
        self._offset = None
        self._show_facets = None
        self._sort_by = None
        self.discriminator = None

        if limit is not None:
            self.limit = limit
        if offset is not None:
            self.offset = offset
        if show_facets is not None:
            self.show_facets = show_facets
        if sort_by is not None:
            self.sort_by = sort_by

    @property
    def limit(self):
        """Gets the limit of this PayloadAllOfView.  # noqa: E501


        :return: The limit of this PayloadAllOfView.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PayloadAllOfView.


        :param limit: The limit of this PayloadAllOfView.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this PayloadAllOfView.  # noqa: E501


        :return: The offset of this PayloadAllOfView.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PayloadAllOfView.


        :param offset: The offset of this PayloadAllOfView.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def show_facets(self):
        """Gets the show_facets of this PayloadAllOfView.  # noqa: E501


        :return: The show_facets of this PayloadAllOfView.  # noqa: E501
        :rtype: PayloadAllOfViewShowFacets
        """
        return self._show_facets

    @show_facets.setter
    def show_facets(self, show_facets):
        """Sets the show_facets of this PayloadAllOfView.


        :param show_facets: The show_facets of this PayloadAllOfView.  # noqa: E501
        :type: PayloadAllOfViewShowFacets
        """

        self._show_facets = show_facets

    @property
    def sort_by(self):
        """Gets the sort_by of this PayloadAllOfView.  # noqa: E501


        :return: The sort_by of this PayloadAllOfView.  # noqa: E501
        :rtype: list[object]
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by):
        """Sets the sort_by of this PayloadAllOfView.


        :param sort_by: The sort_by of this PayloadAllOfView.  # noqa: E501
        :type: list[object]
        """

        self._sort_by = sort_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PayloadAllOfView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PayloadAllOfView):
            return True

        return self.to_dict() != other.to_dict()
