# coding: utf-8

"""
    Ratings API

    Service which holds ratings of various targets, like recipes.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.rating_summaries_target_namespace_target_id_get200_application_json_response import RatingSummariesTargetNamespaceTargetIdGet200ApplicationJsonResponse  # noqa: E501
from openapi_client.rest import ApiException


class TestRatingSummariesTargetNamespaceTargetIdGet200ApplicationJsonResponse(unittest.TestCase):
    """RatingSummariesTargetNamespaceTargetIdGet200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRatingSummariesTargetNamespaceTargetIdGet200ApplicationJsonResponse(self):
        """Test RatingSummariesTargetNamespaceTargetIdGet200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.rating_summaries_target_namespace_target_id_get200_application_json_response.RatingSummariesTargetNamespaceTargetIdGet200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
