# coding: utf-8

"""
    Ratings API

    Service which holds ratings of various targets, like recipes.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rating
from rating.models.health_get200_application_json_response import HealthGet200ApplicationJsonResponse  # noqa: E501
from rating.rest import ApiException


class TestHealthGet200ApplicationJsonResponse(unittest.TestCase):
    """HealthGet200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthGet200ApplicationJsonResponse(self):
        """Test HealthGet200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rating.models.health_get200_application_json_response.HealthGet200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
