# coding: utf-8

"""
    Ratings API

    Service which holds ratings of various targets, like recipes.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.rating_summaries_api import RatingSummariesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRatingSummariesApi(unittest.TestCase):
    """RatingSummariesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.rating_summaries_api.RatingSummariesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_rating_summaries_targetnamespace(self):
        """Test case for get_rating_summaries_targetnamespace

        List rating summaries in a given target namespace.  # noqa: E501
        """
        pass

    def test_get_rating_summaries_targetnamespace_targetid(self):
        """Test case for get_rating_summaries_targetnamespace_targetid

        Return single rating summary.  # noqa: E501
        """
        pass

    def test_post_rating_summaries_targetnamespace(self):
        """Test case for post_rating_summaries_targetnamespace

        List rating summaries in a given target namespace.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
