# coding: utf-8

"""
    Ratings API

    Service which holds ratings of various targets, like recipes.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rating
from rating.models.session_delete200_application_json_response import SessionDelete200ApplicationJsonResponse  # noqa: E501
from rating.rest import ApiException


class TestSessionDelete200ApplicationJsonResponse(unittest.TestCase):
    """SessionDelete200ApplicationJsonResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionDelete200ApplicationJsonResponse(self):
        """Test SessionDelete200ApplicationJsonResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rating.models.session_delete200_application_json_response.SessionDelete200ApplicationJsonResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
