# coding: utf-8

"""
    Ratings API

    Service which holds ratings of various targets, like recipes.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rating
from rating.models.rating_response_all_of1 import RatingResponseAllOf1  # noqa: E501
from rating.rest import ApiException


class TestRatingResponseAllOf1(unittest.TestCase):
    """RatingResponseAllOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRatingResponseAllOf1(self):
        """Test RatingResponseAllOf1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rating.models.rating_response_all_of1.RatingResponseAllOf1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
