# coding: utf-8

"""
    Pricing & Availability API

    Pricing & Availability API is a REST-like API which integrates to POS and knows up to date pricing and product availability data for each store. This service can also be used to create and fill temporary shopping baskets, that are kept for 24 hours before they are automatically deleted.    **NOTE:** The API returns money in the responses. You should NOT use that data for actual payment transactions. They are only meant for displaying purposes, but they should work well enough for hackathon purposes.    API requests are only served over HTTPS, using TLS 1.0, 1.1, and 1.2. Requests will not be honored over plaintext HTTP.    Use of `accept: application/json` and `content-type: application/json` headers is required when applicable.    The API uses UTF-8 character encoding for all responses. Some fields may include characters that are not in the ASCII range.    Authentication is accomplished by providing `Ocp-Apim-Subscription-Key` header with your subscription key as the value.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from api.pricing.pricing.configuration import Configuration


class PromotionV2(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'type': 'int',
        'start_date': 'date',
        'end_date': 'date',
        'price': 'float',
        'max': 'float',
        'basket': 'str',
        'baskets': 'list[object]',
        'batch_price': 'float',
        'batch_size': 'float',
        'discount_percentage': 'float'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'price': 'price',
        'max': 'max',
        'basket': 'basket',
        'baskets': 'baskets',
        'batch_price': 'batchPrice',
        'batch_size': 'batchSize',
        'discount_percentage': 'discountPercentage'
    }

    def __init__(self, id=None, type=None, start_date=None, end_date=None, price=None, max=None, basket=None, baskets=None, batch_price=None, batch_size=None, discount_percentage=None, local_vars_configuration=None):  # noqa: E501
        """PromotionV2 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._type = None
        self._start_date = None
        self._end_date = None
        self._price = None
        self._max = None
        self._basket = None
        self._baskets = None
        self._batch_price = None
        self._batch_size = None
        self._discount_percentage = None
        self.discriminator = None

        self.id = id
        self.type = type
        self.start_date = start_date
        self.end_date = end_date
        if price is not None:
            self.price = price
        if max is not None:
            self.max = max
        if basket is not None:
            self.basket = basket
        if baskets is not None:
            self.baskets = baskets
        if batch_price is not None:
            self.batch_price = batch_price
        if batch_size is not None:
            self.batch_size = batch_size
        if discount_percentage is not None:
            self.discount_percentage = discount_percentage

    @property
    def id(self):
        """Gets the id of this PromotionV2.  # noqa: E501


        :return: The id of this PromotionV2.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PromotionV2.


        :param id: The id of this PromotionV2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this PromotionV2.  # noqa: E501


        :return: The type of this PromotionV2.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PromotionV2.


        :param type: The type of this PromotionV2.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def start_date(self):
        """Gets the start_date of this PromotionV2.  # noqa: E501


        :return: The start_date of this PromotionV2.  # noqa: E501
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this PromotionV2.


        :param start_date: The start_date of this PromotionV2.  # noqa: E501
        :type: date
        """
        if self.local_vars_configuration.client_side_validation and start_date is None:  # noqa: E501
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this PromotionV2.  # noqa: E501


        :return: The end_date of this PromotionV2.  # noqa: E501
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this PromotionV2.


        :param end_date: The end_date of this PromotionV2.  # noqa: E501
        :type: date
        """
        if self.local_vars_configuration.client_side_validation and end_date is None:  # noqa: E501
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def price(self):
        """Gets the price of this PromotionV2.  # noqa: E501


        :return: The price of this PromotionV2.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PromotionV2.


        :param price: The price of this PromotionV2.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def max(self):
        """Gets the max of this PromotionV2.  # noqa: E501


        :return: The max of this PromotionV2.  # noqa: E501
        :rtype: float
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this PromotionV2.


        :param max: The max of this PromotionV2.  # noqa: E501
        :type: float
        """

        self._max = max

    @property
    def basket(self):
        """Gets the basket of this PromotionV2.  # noqa: E501


        :return: The basket of this PromotionV2.  # noqa: E501
        :rtype: str
        """
        return self._basket

    @basket.setter
    def basket(self, basket):
        """Sets the basket of this PromotionV2.


        :param basket: The basket of this PromotionV2.  # noqa: E501
        :type: str
        """

        self._basket = basket

    @property
    def baskets(self):
        """Gets the baskets of this PromotionV2.  # noqa: E501


        :return: The baskets of this PromotionV2.  # noqa: E501
        :rtype: list[object]
        """
        return self._baskets

    @baskets.setter
    def baskets(self, baskets):
        """Sets the baskets of this PromotionV2.


        :param baskets: The baskets of this PromotionV2.  # noqa: E501
        :type: list[object]
        """

        self._baskets = baskets

    @property
    def batch_price(self):
        """Gets the batch_price of this PromotionV2.  # noqa: E501


        :return: The batch_price of this PromotionV2.  # noqa: E501
        :rtype: float
        """
        return self._batch_price

    @batch_price.setter
    def batch_price(self, batch_price):
        """Sets the batch_price of this PromotionV2.


        :param batch_price: The batch_price of this PromotionV2.  # noqa: E501
        :type: float
        """

        self._batch_price = batch_price

    @property
    def batch_size(self):
        """Gets the batch_size of this PromotionV2.  # noqa: E501


        :return: The batch_size of this PromotionV2.  # noqa: E501
        :rtype: float
        """
        return self._batch_size

    @batch_size.setter
    def batch_size(self, batch_size):
        """Sets the batch_size of this PromotionV2.


        :param batch_size: The batch_size of this PromotionV2.  # noqa: E501
        :type: float
        """

        self._batch_size = batch_size

    @property
    def discount_percentage(self):
        """Gets the discount_percentage of this PromotionV2.  # noqa: E501


        :return: The discount_percentage of this PromotionV2.  # noqa: E501
        :rtype: float
        """
        return self._discount_percentage

    @discount_percentage.setter
    def discount_percentage(self, discount_percentage):
        """Sets the discount_percentage of this PromotionV2.


        :param discount_percentage: The discount_percentage of this PromotionV2.  # noqa: E501
        :type: float
        """

        self._discount_percentage = discount_percentage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PromotionV2):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PromotionV2):
            return True

        return self.to_dict() != other.to_dict()
