# coding: utf-8

"""
    Ingredients API

    Ingredient API is a REST-like API which keeps track of recipe ingredients and is integrated to the internal recipe creation tool (Reseptipankki). This service also integrates to Search API, which provides endpoints for searching default products for ingredients.    API requests are only served over HTTPS, using TLS 1.0, 1.1, and 1.2. Requests will not be honored over plaintext HTTP.    Use of `accept: application/json` and `content-type: application/json` headers is required when applicable.    The API uses UTF-8 character encoding for all responses. Some fields may include characters that are not in the ASCII range.    As every other Kesko API service in this hackathon, authentication is accomplished by providing `Ocp-Apim-Subscription-Key` header with your subscription key as the value.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ingredients
from ingredients.api.departments_api import DepartmentsApi  # noqa: E501
from ingredients.rest import ApiException


class TestDepartmentsApi(unittest.TestCase):
    """DepartmentsApi unit test stubs"""

    def setUp(self):
        self.api = ingredients.api.departments_api.DepartmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_departments(self):
        """Test case for get_departments

        List all departments.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
